In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [5]:
dataset = pd.read_csv("dataSet/titanic.csv")
dataset.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [6]:
#raplace female to 0 and male to 1, in Sex column
dataset['Sex']=dataset['Sex'].replace(['female','male'],[0,1])
dataset.head()

Survived  Pclass                                               Name  Sex  \
0         0       3                             Mr. Owen Harris Braund    1   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...    0   
2         1       3                              Miss. Laina Heikkinen    0   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle    0   
4         0       3                            Mr. William Henry Allen    1   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833  
2  26.0                        0                        0   7.9250  
3  35.0                        1                        0  53.1000  
4  35.0                        0                        0   8.0500

In [25]:
#Generate futear X and target y
X = dataset[['Pclass','Age','Sex','Age','Siblings/Spouses Aboard','Parents/Children Aboard', 'Fare']].values
y = dataset[['Survived']].values

In [8]:
print(X.shape," ",y.shape)
X

(887, 7)   (887, 1)


array([[ 3.    , 22.    ,  1.    , ...,  1.    ,  0.    ,  7.25  ],
       [ 1.    , 38.    ,  0.    , ...,  1.    ,  0.    , 71.2833],
       [ 3.    , 26.    ,  0.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 3.    ,  7.    ,  0.    , ...,  1.    ,  2.    , 23.45  ],
       [ 1.    , 26.    ,  1.    , ...,  0.    ,  0.    , 30.    ],
       [ 3.    , 32.    ,  1.    , ...,  0.    ,  0.    ,  7.75  ]])

In [26]:
print(y[:5])
y = y.ravel()
print(y[:5])

[[0]
 [1]
 [1]
 [1]
 [0]]
[0 1 1 1 0]


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [19]:
# Normalizing data
from sklearn.preprocessing import Normalizer

scaler= Normalizer().fit(X_train) # the scaler is fitted to the  dataset
X_train= scaler.transform(X_train) # the scaler is applied to the dataset
X_train

array([[0.07412352, 0.6918195 , 0.02470784, ..., 0.        , 0.        ,
        0.19148575],
       [0.06933116, 0.69331161, 0.02311039, ..., 0.        , 0.        ,
        0.18247499],
       [0.00194282, 0.06799871, 0.        , ..., 0.        , 0.        ,
        0.99536354],
       ...,
       [0.01372021, 0.61740943, 0.01372021, ..., 0.        , 0.        ,
        0.48706744],
       [0.02796656, 0.69916395, 0.        , ..., 0.        , 0.        ,
        0.14682443],
       [0.01495066, 0.46347057, 0.01495066, ..., 0.        , 0.        ,
        0.75494571]])

In [20]:
#import Logistic regression model and use it to train our data and get the final parameter (bias and weights)
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_train, y_train)

LogisticRegression()

In [21]:
y_pred = log.predict(X_test)

In [22]:
print(log.coef_, log.intercept_)

[[-0.87750105  0.20316732 -1.46043864  0.20316732 -1.30800134 -0.04952973
   2.43293651]] [-1.76479238]


In [23]:
s = log.score(X, y)
s

0.6865839909808342

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y, y_pred)

print(accuracy)

In [ ]:
print(y)

In [ ]:
print(y_pred)

In [ ]:
dataset.groupby('Survived').size()

In [ ]:
print(0," ",len(y_pred[y_pred==0]))
print(1," ",len(y_pred[y_pred==1]))